checks:
  php:
    code_rating: true
    duplication: true
    verify_property_names: true
    uppercase_constants: true
    unused_variables: true
    unused_properties: true
    unused_methods: true
    single_namespace_per_use: true

coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
        negation: false
      other:
        after_type_cast: false

tools:
  external_code_coverage: false
  php_code_coverage: false
  php_code_sniffer:
    config: { standard: 'PSR2' }
  php_changetracking: false
  php_sim: false
  php_mess_detector: true
  php_pdepend: true
  php_analyzer: false
  sensiolabs_security_checker: true

filter:
  paths:
  - 'src/*'
  excluded_paths:
  - 'tests/*'
  - 'vendor/*'

build:
  environment:
    php:
      version: '5.6'
      ini:
        'always_populate_raw_post_data': '-1'

  nodes:
    analysis:
      tests:
        override:
        - php-scrutinizer-run

      dependencies:
        override:
        - { command: 'composer install --no-interaction', idle_timeout: 600 }

    tests-and-coverage:
      tests:
        override:
        - vendor/bin/phpunit

      dependencies:
        override:
        - { command: 'composer install --no-interaction', idle_timeout: 600 }

  cache:
    directories: [ vendor/, ~/.composer/cache ]

build_failure_conditions:
- 'elements.rating(<= B).new.exists'
- 'issues.label("coding-style").new.exists'
- 'issues.new.exists'
- 'project.metric("scrutinizer.quality", < 9.00)'